name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Bazelisk
        uses: mishas/setup-bazelisk-action@v1

      - name: Build
        run: bazel build //pkg/demo
